version: "3.3"

networks:
  main:
    driver: bridge

services:
  db:
    image: postgres:12.8
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - 5432:5432
    networks:
      - main

volumes:
  postgres_data: