"""Add user relation

Revision ID: 43b28a13541a
Revises: df33d2ecb70b
Create Date: 2023-01-18 17:16:24.484666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43b28a13541a'
down_revision = 'df33d2ecb70b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('user_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'user_id')
    # ### end Alembic commands ###
