"""rm user fileds

Revision ID: 7f7acb68ee2b
Revises: 43b28a13541a
Create Date: 2023-01-21 17:09:21.132156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7acb68ee2b'
down_revision = '43b28a13541a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'successed_tasks')
    op.drop_column('users', 'streak')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('streak', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('successed_tasks', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
